version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nineos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nineos
      POSTGRES_PASSWORD: nineos_pass
      POSTGRES_DB: nineos_db
    ports:
      - '5432:5432'
    volumes:
      - nineos_pgdata:/var/lib/postgresql/data

volumes:
  nineos_pgdata:
